apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: ecommerce/service-registry:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef:
                name: ecommerce-platform-config
