apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-platform-config
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SCHEMA_REGISTRY_URL: http://schema-registry:8081
  ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
