server:
  port: 8082

spring:
  application:
    name: inventory-service
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://localhost:5432/inventorydb}
    username: ${INVENTORY_DB_USER:inventory_user}
    password: ${INVENTORY_DB_PASSWORD:inventory_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
