server:
  port: 8083

spring:
  application:
    name: payment-service
  datasource:
    url: ${PAYMENT_DB_URL:jdbc:postgresql://localhost:5432/paymentdb}
    username: ${PAYMENT_DB_USER:payment_user}
    password: ${PAYMENT_DB_PASSWORD:payment_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
